name: garbage_locator
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  path_provider: ^2.1.3 #android sdk 16+, ios 12+
  image_picker: ^1.1.1 #android sdk 21+, ios 12.0+
  equatable: ^2.0.5
  floor: ^1.5.0
  #sqflite: ^2.3.3+1
  provider: ^6.1.2
  flutter_map: ^6.1.0
  url_launcher: ^6.2.6
  logger: ^2.3.0
  exif: ^3.3.0
  location: ^6.0.2
  geocoding: ^3.0.0
  flutter_map_cache: ^1.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  flutter_map_animations: ^0.6.0
  connectivity_plus: ^6.0.3
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  json_serializable: ^6.8.0
  uuid: ^4.4.0
  firebase_storage: ^11.7.6
  flutter_conditional_rendering: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/
    - assets/vector/

