name: garbage_locator
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  path_provider: ^2.1.3
  image_picker: ^1.1.1
  equatable: ^2.0.5
  floor: ^1.5.0
  sqflite: ^2.3.3+1
  provider: ^6.1.2
  flutter_map: ^6.1.0
  url_launcher: ^6.2.6
  logger: ^2.2.0
  exif: ^3.3.0
  location: ^6.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/

