// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzXTi8BKwnNb-QGxZe14WIWjG1pA14VUk',
    appId: '1:765011984405:web:a705a7faaa17cd31f68e1c',
    messagingSenderId: '765011984405',
    projectId: 'garbage-locator-e6468',
    authDomain: 'garbage-locator-e6468.firebaseapp.com',
    storageBucket: 'garbage-locator-e6468.appspot.com',
    measurementId: 'G-3D4WYRVYC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhHWeaDW705GMoDUEX-3vtfZ1YcoiU7Mg',
    appId: '1:765011984405:android:0461255265281cf4f68e1c',
    messagingSenderId: '765011984405',
    projectId: 'garbage-locator-e6468',
    storageBucket: 'garbage-locator-e6468.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Js6ut_Ar4tp08TVeP0ca-wwRgxSwn0U',
    appId: '1:765011984405:ios:2740cd00fe2ab86ef68e1c',
    messagingSenderId: '765011984405',
    projectId: 'garbage-locator-e6468',
    storageBucket: 'garbage-locator-e6468.appspot.com',
    iosBundleId: 'com.example.garbageLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Js6ut_Ar4tp08TVeP0ca-wwRgxSwn0U',
    appId: '1:765011984405:ios:2740cd00fe2ab86ef68e1c',
    messagingSenderId: '765011984405',
    projectId: 'garbage-locator-e6468',
    storageBucket: 'garbage-locator-e6468.appspot.com',
    iosBundleId: 'com.example.garbageLocator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzXTi8BKwnNb-QGxZe14WIWjG1pA14VUk',
    appId: '1:765011984405:web:7c55b8cc4bf7fe42f68e1c',
    messagingSenderId: '765011984405',
    projectId: 'garbage-locator-e6468',
    authDomain: 'garbage-locator-e6468.firebaseapp.com',
    storageBucket: 'garbage-locator-e6468.appspot.com',
    measurementId: 'G-GJBTV1ZJ1G',
  );

}